theme: jekyll-theme-hacker
show_downloads: true
github:
  zip_url: https://github.com/lucho1/DevelopmentProject/releases/download/DayBreak-v1.0/DayBreak_v1_0.zip
  tar_url: https://github.com/lucho1/DevelopmentProject/archive/DayBreak-v1.0.tar.gz
